### ISSUE TITLE
Possible injected Malware

### ISSUE THREAD

**Issue by Tricky-Ricky** [stellarterm/stellarterm-desktop-client#5]
Went to download the wallet from https://stellarterm.com/#

Had this pop up on my browser leaving me having to force close via Task Manager - Before I did close it though - It was overlapping other applications on my PC - and now my Quick Access in file explorer is not working properly... Fresh Install of Windows 10 May update yesterday.

https://cdn.discordapp.com/attachments/577450463268438026/582875929920012298/unknown.png

Uploaded it to a community I am part of in case it is Malware, Certainly acts like it and AVG, MalwareBytes and Windows Defender soes not detect it anywhere.

Apologies if this is false positive - But please double check

**Comment by pitsevich** [comment]
@Tricky-Ricky Please clarify which build you've downloaded from here:
https://github.com/stellarterm/stellarterm-desktop-client/releases

Is this the one: "Pre-release StellarTerm Desktop Client v1204" ?
Most likely it happens on Windows because the build is not signed yet - but we'll check.

Let me know.

**Comment by pitsevich** [comment]
@Tricky-Ricky Thanks again for the report!  We confirmed that the warnings are visible on Windows because the build is not signed.

We will release a new desktop version of Stellarterm next week, it will be signed and should not trigger any warnings.

**Comment by Tricky-Ricky** [comment]
Hi pitsevich
Can confirm it is still not fixed - It now pops up immediatly as you join the site:

https://cdn.discordapp.com/attachments/277762861852262410/601776931205152769/unknown.png

Albeit this time, It did not jump around windows and subsequently closed after a short while
